In [2]:
import pandas as pd
import requests

In [ ]:
https://simfin.com/api/v1/info/find-id/ticker/AAPL?api-key=YOUR_API_KEY

In [4]:
YOUR_API_KEY = "ENTER API KEY"

In [14]:
base_url = "https://simfin.com/api/v1/info/find-id/ticker/AAPL?api-key={0}".format(YOUR_API_KEY)
r = requests.get(base_url)
r_json = r.json()
name = r_json[1]["name"]
print(r_json)
print(name)

[{'simId': 65735, 'ticker': 'AAPL', 'name': 'AMGEN INC'}, {'simId': 111052, 'ticker': 'AAPL', 'name': 'APPLE INC'}]
APPLE INC

In [21]:
#find simId

tickerStr = "AAPL"

base_url = "https://simfin.com/api/v1/info/find-id/ticker/{0}?api-key={1}".format(tickerStr, YOUR_API_KEY)
print(base_url)
r = requests.get(base_url)
print(r)
r_json = r.json()
print(r_json)

https://simfin.com/api/v1/info/find-id/ticker/AAPL?api-key=YoLnI8a7Qlc0N6LBqVtWfpHVRp1saj1U
<Response [200]>
[{'simId': 65735, 'ticker': 'AAPL', 'name': 'AMGEN INC'}, {'simId': 111052, 'ticker': 'AAPL', 'name': 'APPLE INC'}]

In [23]:
#all companies in database

base_url = "https://simfin.com/api/v1/info/all-entities?api-key={0}".format(YOUR_API_KEY)
print(base_url)
r = requests.get(base_url)
print(r)
r_json = r.json()
test = r_json[100]["name"]
print(test)

https://simfin.com/api/v1/info/all-entities?api-key=YoLnI8a7Qlc0N6LBqVtWfpHVRp1saj1U
<Response [200]>
ALNYLAM PHARMACEUTICALS, INC.

In [24]:
df = pd.DataFrame(r_json)
df

                                                 name   simId ticker
0                               1 800 FLOWERS COM INC  247341   FLWS
1                                    21st Century Fox     242    FOX
2                                     3D SYSTEMS CORP  545133    DDD
3                                                  3M   22219    MMM
4                                        8X8 INC /DE/   36662   EGHT
5                            99 CENTS ONLY STORES LLC  210709   NCSO
6                        A-Mark Precious Metals, Inc.  259435   AMRK
7                                     A. H. Belo Corp  652799    AHC
8                                            AAR CORP  671123    AIR
9                                         AARON'S INC  441241    AAN
10                                         ABAXIS INC   36105   ABAX
11                                ABBOTT LABORATORIES   63877    ABT
12                                        AbbVie Inc.   61199   ABBV
13                        ABERCROMBIE & FITCH CO /DE/  188522    ANF
14                                        Abiomed Inc  445587   ABMD
15                            ABM INDUSTRIES INC /DE/  199984    ABM
16                        Acacia Communications, Inc.  353923   ACIA
17                      Acadia Healthcare Company Inc  445598   ACHC
18                         Acadia Pharmaceuticals Inc  445591   ACAD
19                                ACADIA REALTY TRUST  664572    AKR
20                                    Accelerize Inc.  655300   ACLZ
21                                      Accenture plc   61372    ACN
22                                   ACCO BRANDS Corp  120923   ACCO
23                                        ACCURAY INC  173115   ARAY
24                                      ACCURIDE CORP  671043    ACW
25                         ACELRX PHARMACEUTICALS INC  113247   ACRX
26                                         ACETO CORP  191612   ACET
27                                      Actavis, Inc.  353702    ACT
28                                   ACTIVE POWER INC   95192   ACPW
29                                Activision Blizzard     243   ATVI
...                                               ...     ...    ...
1846                       WORTHINGTON INDUSTRIES INC  332221    WOR
1847                                   WPX Energy Inc  449237    WPX
1848                             WSI INDUSTRIES, INC.   65297   WSCI
1849                           WYNDHAM WORLDWIDE CORP  116466    WYN
1850                                 Wynn Resorts Ltd  378245   WYNN
1851                                    XBiotech Inc.  156298   XBIT
1852                                  Xcel Energy Inc  378246    XEL
1853                                      Xcerra Corp  247530   XCRA
1854                                      Xerox Corp.  378247    XRX
1855                                       XILINX INC  396684   XLNX
1856                                 XINHUA CHINA LTD  662912   XHUA
1857                                    XO GROUP INC.  651859   XOXO
1858                              XPO Logistics, Inc.  364942    XPO
1859                                       Xylem Inc.  124467    XYL
1860                                        YAHOO INC  257807   YHOO
1861                                             YELP  440174   YELP
1862  Yinhang Internet Technologies Development, Inc.  660011   YITD
1863                                   YUM BRANDS INC   98663    YUM
1864                        Zayo Group Holdings, Inc.  694556   ZAYO
1865                                      Zedge, Inc.  372279   ZEDG
1866                           ZHONE TECHNOLOGIES INC  202955   ZHNE
1867                               ZILLOW GROUP, INC.  647182     ZG
1868                           Zimmer Biomet Holdings  378249    ZBH
1869                                    Zions Bancorp  378250   ZION
1870                                           Zoetis  378251    ZTS
1871                           Zoned Properties, Inc.  687925   ZDPY
1872                               ZONZIA MEDIA, INC.  664525   ZONX
1873                                       Zumiez Inc   45730   ZUMZ
1874                                        ZYNEX INC  171401   ZYXI
1875                                        ZYNGA INC  418866   ZNGA

[1876 rows x 3 columns]

In [27]:
df = df.set_index("ticker")
df

                                                   name   simId
ticker
FLWS                              1 800 FLOWERS COM INC  247341
FOX                                    21st Century Fox     242
DDD                                     3D SYSTEMS CORP  545133
MMM                                                  3M   22219
EGHT                                       8X8 INC /DE/   36662
NCSO                           99 CENTS ONLY STORES LLC  210709
AMRK                       A-Mark Precious Metals, Inc.  259435
AHC                                     A. H. Belo Corp  652799
AIR                                            AAR CORP  671123
AAN                                         AARON'S INC  441241
ABAX                                         ABAXIS INC   36105
ABT                                 ABBOTT LABORATORIES   63877
ABBV                                        AbbVie Inc.   61199
ANF                         ABERCROMBIE & FITCH CO /DE/  188522
ABMD                                        Abiomed Inc  445587
ABM                             ABM INDUSTRIES INC /DE/  199984
ACIA                        Acacia Communications, Inc.  353923
ACHC                      Acadia Healthcare Company Inc  445598
ACAD                         Acadia Pharmaceuticals Inc  445591
AKR                                 ACADIA REALTY TRUST  664572
ACLZ                                    Accelerize Inc.  655300
ACN                                       Accenture plc   61372
ACCO                                   ACCO BRANDS Corp  120923
ARAY                                        ACCURAY INC  173115
ACW                                       ACCURIDE CORP  671043
ACRX                         ACELRX PHARMACEUTICALS INC  113247
ACET                                         ACETO CORP  191612
ACT                                       Actavis, Inc.  353702
ACPW                                   ACTIVE POWER INC   95192
ATVI                                Activision Blizzard     243
...                                                 ...     ...
WOR                          WORTHINGTON INDUSTRIES INC  332221
WPX                                      WPX Energy Inc  449237
WSCI                               WSI INDUSTRIES, INC.   65297
WYN                              WYNDHAM WORLDWIDE CORP  116466
WYNN                                   Wynn Resorts Ltd  378245
XBIT                                      XBiotech Inc.  156298
XEL                                     Xcel Energy Inc  378246
XCRA                                        Xcerra Corp  247530
XRX                                         Xerox Corp.  378247
XLNX                                         XILINX INC  396684
XHUA                                   XINHUA CHINA LTD  662912
XOXO                                      XO GROUP INC.  651859
XPO                                 XPO Logistics, Inc.  364942
XYL                                          Xylem Inc.  124467
YHOO                                          YAHOO INC  257807
YELP                                               YELP  440174
YITD    Yinhang Internet Technologies Development, Inc.  660011
YUM                                      YUM BRANDS INC   98663
ZAYO                          Zayo Group Holdings, Inc.  694556
ZEDG                                        Zedge, Inc.  372279
ZHNE                             ZHONE TECHNOLOGIES INC  202955
ZG                                   ZILLOW GROUP, INC.  647182
ZBH                              Zimmer Biomet Holdings  378249
ZION                                      Zions Bancorp  378250
ZTS                                              Zoetis  378251
ZDPY                             Zoned Properties, Inc.  687925
ZONX                                 ZONZIA MEDIA, INC.  664525
ZUMZ                                         Zumiez Inc   45730
ZYXI                                          ZYNEX INC  171401
ZNGA                                          ZYNGA INC  418866

[1876 rows x 2 columns]

In [34]:
df.loc["RUBI"]["simId"]

683438

In [39]:
#company overview

companyId = df.loc["RUBI"]["simId"]

base_url = "https://simfin.com/api/v1/companies/id/{0}?api-key={1}".format(companyId, YOUR_API_KEY)
r = requests.get(base_url)
r_json = r.json()
print(r_json)

{'simId': 683438, 'ticker': 'RUBI', 'name': 'RUBICON PROJECT, INC.', 'fyearEnd': 12, 'employees': 514, 'sectorName': 'Application Software', 'sectorCode': 101003}

In [38]:
df_overview = pd.DataFrame(r_json, index=[0])
df_overview

,employees,fyearEnd,name,sectorCode,sectorName,simId,ticker
0,514,12,"RUBICON PROJECT, INC.",101003,Application Software,683438,RUBI

In [40]:
#list of available company statements

companyId = df.loc["RUBI"]["simId"]

base_url = "https://simfin.com/api/v1/companies/id/{0}/statements/list?api-key={1}".format(companyId, YOUR_API_KEY)
r = requests.get(base_url)
r_json = r.json()
print(r_json)

{'pl': [{'period': 'TTM', 'fyear': 2018, 'calculated': True}, {'period': 'H1', 'fyear': 2018, 'calculated': False}, {'period': 'Q2', 'fyear': 2018, 'calculated': False}, {'period': 'Q1', 'fyear': 2018, 'calculated': False}, {'period': 'TTM-1', 'fyear': 2017, 'calculated': True}, {'period': 'FY', 'fyear': 2017, 'calculated': False}, {'period': 'Q4', 'fyear': 2017, 'calculated': True}, {'period': 'H2', 'fyear': 2017, 'calculated': True}, {'period': '9M', 'fyear': 2017, 'calculated': False}, {'period': 'Q3', 'fyear': 2017, 'calculated': False}, {'period': 'H1', 'fyear': 2017, 'calculated': False}, {'period': 'Q2', 'fyear': 2017, 'calculated': False}, {'period': 'Q1', 'fyear': 2017, 'calculated': False}, {'period': 'TTM-2', 'fyear': 2016, 'calculated': True}, {'period': 'FY', 'fyear': 2016, 'calculated': False}, {'period': 'Q4', 'fyear': 2016, 'calculated': True}, {'period': 'H2', 'fyear': 2016, 'calculated': True}, {'period': '9M', 'fyear': 2016, 'calculated': False}, {'period': 'Q3', 'fyear': 2016, 'calculated': False}, {'period': 'H1', 'fyear': 2016, 'calculated': False}, {'period': 'Q2', 'fyear': 2016, 'calculated': False}, {'period': 'Q1', 'fyear': 2016, 'calculated': False}, {'period': 'FY', 'fyear': 2015, 'calculated': False}, {'period': 'Q4', 'fyear': 2015, 'calculated': True}, {'period': 'H2', 'fyear': 2015, 'calculated': True}, {'period': '9M', 'fyear': 2015, 'calculated': False}, {'period': 'Q3', 'fyear': 2015, 'calculated': False}, {'period': 'H1', 'fyear': 2015, 'calculated': False}, {'period': 'Q2', 'fyear': 2015, 'calculated': False}, {'period': 'Q1', 'fyear': 2015, 'calculated': False}, {'period': 'FY', 'fyear': 2014, 'calculated': False}, {'period': 'Q4', 'fyear': 2014, 'calculated': True}, {'period': 'H2', 'fyear': 2014, 'calculated': True}, {'period': '9M', 'fyear': 2014, 'calculated': False}, {'period': 'Q3', 'fyear': 2014, 'calculated': False}, {'period': 'H1', 'fyear': 2014, 'calculated': False}, {'period': 'Q2', 'fyear': 2014, 'calculated': False}, {'period': 'Q1', 'fyear': 2014, 'calculated': False}, {'period': 'FY', 'fyear': 2013, 'calculated': False}, {'period': 'Q4', 'fyear': 2013, 'calculated': True}, {'period': 'H2', 'fyear': 2013, 'calculated': True}, {'period': '9M', 'fyear': 2013, 'calculated': False}, {'period': 'Q3', 'fyear': 2013, 'calculated': False}, {'period': 'H1', 'fyear': 2013, 'calculated': False}, {'period': 'Q2', 'fyear': 2013, 'calculated': False}, {'period': 'Q1', 'fyear': 2013, 'calculated': False}, {'period': 'FY', 'fyear': 2012, 'calculated': False}], 'bs': [{'period': 'TTM', 'fyear': 2018, 'calculated': True}, {'period': 'Q2', 'fyear': 2018, 'calculated': False}, {'period': 'Q1', 'fyear': 2018, 'calculated': False}, {'period': 'TTM-1', 'fyear': 2017, 'calculated': True}, {'period': 'Q4', 'fyear': 2017, 'calculated': False}, {'period': 'Q3', 'fyear': 2017, 'calculated': False}, {'period': 'Q2', 'fyear': 2017, 'calculated': False}, {'period': 'Q1', 'fyear': 2017, 'calculated': False}, {'period': 'TTM-2', 'fyear': 2016, 'calculated': True}, {'period': 'Q4', 'fyear': 2016, 'calculated': False}, {'period': 'Q3', 'fyear': 2016, 'calculated': False}, {'period': 'Q2', 'fyear': 2016, 'calculated': False}, {'period': 'Q1', 'fyear': 2016, 'calculated': False}, {'period': 'Q4', 'fyear': 2015, 'calculated': False}, {'period': 'Q3', 'fyear': 2015, 'calculated': False}, {'period': 'Q2', 'fyear': 2015, 'calculated': False}, {'period': 'Q1', 'fyear': 2015, 'calculated': False}, {'period': 'Q4', 'fyear': 2014, 'calculated': False}, {'period': 'Q3', 'fyear': 2014, 'calculated': False}, {'period': 'Q2', 'fyear': 2014, 'calculated': False}, {'period': 'Q1', 'fyear': 2014, 'calculated': False}, {'period': 'Q4', 'fyear': 2013, 'calculated': False}], 'cf': [{'period': 'TTM', 'fyear': 2018, 'calculated': True}, {'period': 'H1', 'fyear': 2018, 'calculated': False}, {'period': 'Q2', 'fyear': 2018, 'calculated': True}, {'period': 'Q1', 'fyear': 2018, 'calculated': False}, {'period': 'TTM-1', 'fyear': 2017, 'calculated': True}, {'period': 'FY', 'fyear': 2017, 'calculated': False}, {'period': 'Q4', 'fyear': 2017, 'calculated': True}, {'period': 'H2', 'fyear': 2017, 'calculated': True}, {'period': '9M', 'fyear': 2017, 'calculated': False}, {'period': 'Q3', 'fyear': 2017, 'calculated': True}, {'period': 'H1', 'fyear': 2017, 'calculated': False}, {'period': 'Q2', 'fyear': 2017, 'calculated': True}, {'period': 'Q1', 'fyear': 2017, 'calculated': False}, {'period': 'TTM-2', 'fyear': 2016, 'calculated': True}, {'period': 'FY', 'fyear': 2016, 'calculated': False}, {'period': 'Q4', 'fyear': 2016, 'calculated': True}, {'period': 'H2', 'fyear': 2016, 'calculated': True}, {'period': '9M', 'fyear': 2016, 'calculated': False}, {'period': 'Q3', 'fyear': 2016, 'calculated': True}, {'period': 'H1', 'fyear': 2016, 'calculated': False}, {'period': 'Q2', 'fyear': 2016, 'calculated': True}, {'period': 'Q1', 'fyear': 2016, 'calculated': False}, {'period': 'FY', 'fyear': 2015, 'calculated': False}, {'period': 'Q4', 'fyear': 2015, 'calculated': True}, {'period': 'H2', 'fyear': 2015, 'calculated': True}, {'period': '9M', 'fyear': 2015, 'calculated': False}, {'period': 'Q3', 'fyear': 2015, 'calculated': True}, {'period': 'H1', 'fyear': 2015, 'calculated': False}, {'period': 'Q2', 'fyear': 2015, 'calculated': True}, {'period': 'Q1', 'fyear': 2015, 'calculated': False}, {'period': 'FY', 'fyear': 2014, 'calculated': False}, {'period': 'Q4', 'fyear': 2014, 'calculated': True}, {'period': 'H2', 'fyear': 2014, 'calculated': True}, {'period': '9M', 'fyear': 2014, 'calculated': False}, {'period': 'Q3', 'fyear': 2014, 'calculated': True}, {'period': 'H1', 'fyear': 2014, 'calculated': False}, {'period': 'Q2', 'fyear': 2014, 'calculated': True}, {'period': 'Q1', 'fyear': 2014, 'calculated': False}, {'period': 'FY', 'fyear': 2013, 'calculated': False}, {'period': 'Q4', 'fyear': 2013, 'calculated': True}, {'period': 'H2', 'fyear': 2013, 'calculated': True}, {'period': '9M', 'fyear': 2013, 'calculated': False}, {'period': 'Q3', 'fyear': 2013, 'calculated': True}, {'period': 'H1', 'fyear': 2013, 'calculated': False}, {'period': 'Q2', 'fyear': 2013, 'calculated': True}, {'period': 'Q1', 'fyear': 2013, 'calculated': False}, {'period': 'FY', 'fyear': 2012, 'calculated': False}]}

In [45]:
#Return data from statements (not standardized)

#stype: "pl" "bs" "cf"
#ptype: "Q1" "Q2" "Q3" "Q4" "H1" "H2" "9M" "FY" "TTM" "TTM-1" "TTM-2"
#fyear: 2015, 2016, 2017, etc

companyId = df.loc["RUBI"]["simId"]

task = {
    "stype":"pl",
    "ptype":"FY",
    "fyear":"2017"
        }


base_url = "https://simfin.com/api/v1/companies/id/{0}/statements/original?api-key={1}".format(companyId, YOUR_API_KEY)
r = requests.get(base_url, task)
r_json = r.json()
print(r_json)

{'calculationScheme': [], 'calculated': False, 'metaData': [{'statementId': '2570361', 'filingDate': '2018-03-15', 'firstPublished': '2018-03-15', 'fyear': 2017, 'period': 'FY', 'restated': False, 'currency': 'USD', 'sourceDescription': None, 'sourceUrl': 'http://www.sec.gov/Archives/edgar/data/1595974/000159597418000020/0001595974-18-000020-index.htm'}], 'values': [{'lineItemId': '683779', 'lineItemName': 'Revenue', 'lineItemType': 'normal', 'value': 155545000}, {'lineItemId': '683780', 'lineItemName': 'Cost of revenue', 'lineItemType': 'normal', 'value': 56836000}, {'lineItemId': '683781', 'lineItemName': 'Sales and Marketing', 'lineItemType': 'normal', 'value': 51794000}, {'lineItemId': '683782', 'lineItemName': 'Technology and development', 'lineItemType': 'normal', 'value': 47500000}, {'lineItemId': '683783', 'lineItemName': 'General and administrative', 'lineItemType': 'normal', 'value': 55596000}, {'lineItemId': '683784', 'lineItemName': 'Restructuring and other exit costs', 'lineItemType': 'normal', 'value': 5959000}, {'lineItemId': '683785', 'lineItemName': 'Impairment of intangible assets and internal use software', 'lineItemType': 'normal', 'value': 4585000}, {'lineItemId': '683786', 'lineItemName': 'Impairment of goodwill', 'lineItemType': 'normal', 'value': 90251000}, {'lineItemId': '683787', 'lineItemName': 'Total expenses', 'lineItemType': 'sum', 'value': 312521000}, {'lineItemId': '683788', 'lineItemName': 'Loss from operations', 'lineItemType': 'sum', 'value': -156976000}, {'lineItemId': '683789', 'lineItemName': 'Interest income, net', 'lineItemType': 'normal', 'value': -908000}, {'lineItemId': '683790', 'lineItemName': 'Other income', 'lineItemType': 'normal', 'value': 688000}, {'lineItemId': '683792', 'lineItemName': 'Foreign exchange (gain) loss, net', 'lineItemType': 'normal', 'value': 1165000}, {'lineItemId': '683793', 'lineItemName': 'Total other income, net', 'lineItemType': 'sum', 'value': -431000}, {'lineItemId': '683794', 'lineItemName': 'Loss before income taxes', 'lineItemType': 'sum', 'value': -156545000}, {'lineItemId': '683795', 'lineItemName': 'Benefit for income taxes', 'lineItemType': 'normal', 'value': -1762000}, {'lineItemId': '683796', 'lineItemName': 'Net Income (Loss)', 'lineItemType': 'sum', 'value': -154783000}]}

In [52]:
df_pl_nonstd = pd.DataFrame(r_json["values"])
df_pl_nonstd

,lineItemId,lineItemName,lineItemType,value
0,683779,Revenue,normal,155545000
1,683780,Cost of revenue,normal,56836000
2,683781,Sales and Marketing,normal,51794000
3,683782,Technology and development,normal,47500000
4,683783,General and administrative,normal,55596000
5,683784,Restructuring and other exit costs,normal,5959000
6,683785,Impairment of intangible assets and internal u...,normal,4585000
7,683786,Impairment of goodwill,normal,90251000
8,683787,Total expenses,sum,312521000
9,683788,Loss from operations,sum,-156976000
10,683789,"Interest income, net",normal,-908000
11,683790,Other income,normal,688000
12,683792,"Foreign exchange (gain) loss, net",normal,1165000
13,683793,"Total other income, net",sum,-431000
14,683794,Loss before income taxes,sum,-156545000
15,683795,Benefit for income taxes,normal,-1762000
16,683796,Net Income (Loss),sum,-154783000

In [55]:
#Return data from statements (standardized)

#stype: "pl" "bs" "cf"
#ptype: "Q1" "Q2" "Q3" "Q4" "H1" "H2" "9M" "FY" "TTM" "TTM-1" "TTM-2"
#fyear: 2015, 2016, 2017, etc

companyId = df.loc["RUBI"]["simId"]

task = {
    "stype":"pl",
    "ptype":"FY",
    "fyear":"2017"
        }

base_url = "https://simfin.com/api/v1/companies/id/{0}/statements/standardised?api-key={1}".format(companyId, YOUR_API_KEY)
r = requests.get(base_url, task)
r_json = r.json()
print(r_json)

{'calculationScheme': [], 'calculated': False, 'industryTemplate': 'general', 'values': [{'tid': '1', 'uid': '1', 'standardisedName': 'Revenue', 'parent_tid': '4', 'displayLevel': '0', 'valueAssigned': '278221000', 'valueCalculated': 0, 'valueChosen': '278221000', 'checkPossible': False}, {'tid': '3', 'uid': '0', 'standardisedName': 'Sales & Services Revenue', 'parent_tid': '1', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '5', 'uid': '0', 'standardisedName': 'Financing Revenue', 'parent_tid': '1', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '6', 'uid': '0', 'standardisedName': 'Other Revenue', 'parent_tid': '1', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '2', 'uid': '2', 'standardisedName': 'Cost of revenue', 'parent_tid': '4', 'displayLevel': '0', 'valueAssigned': '-73247000', 'valueCalculated': 0, 'valueChosen': '-73247000', 'checkPossible': False}, {'tid': '7', 'uid': '0', 'standardisedName': 'Cost of Goods & Services', 'parent_tid': '2', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '8', 'uid': '0', 'standardisedName': 'Cost of Financing Revenue', 'parent_tid': '2', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '9', 'uid': '0', 'standardisedName': 'Cost of Other Revenue', 'parent_tid': '2', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '4', 'uid': '4', 'standardisedName': 'Gross Profit', 'parent_tid': '19', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': 204974000, 'valueChosen': 204974000, 'checkPossible': False}, {'tid': '10', 'uid': '10', 'standardisedName': 'Other Operating Income', 'parent_tid': '19', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '11', 'uid': '11', 'standardisedName': 'Operating Expenses', 'parent_tid': '19', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': -203082000, 'valueChosen': -203082000, 'checkPossible': False}, {'tid': '12', 'uid': '12', 'standardisedName': 'Selling, General & Administrative', 'parent_tid': '11', 'displayLevel': '1', 'valueAssigned': '-151898000', 'valueCalculated': 0, 'valueChosen': '-151898000', 'checkPossible': False}, {'tid': '13', 'uid': '0', 'standardisedName': 'Selling & Marketing', 'parent_tid': '12', 'displayLevel': '2', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '14', 'uid': '0', 'standardisedName': 'General & Administrative', 'parent_tid': '12', 'displayLevel': '2', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '15', 'uid': '15', 'standardisedName': 'Research & Development', 'parent_tid': '11', 'displayLevel': '1', 'valueAssigned': '-51184000', 'valueCalculated': 0, 'valueChosen': '-51184000', 'checkPossible': False}, {'tid': '16', 'uid': '16', 'standardisedName': 'Depreciation & Amortization', 'parent_tid': '11', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '17', 'uid': '17', 'standardisedName': 'Provision For Doubtful Accounts', 'parent_tid': '11', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '18', 'uid': '18', 'standardisedName': 'Other Operating Expense', 'parent_tid': '11', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '19', 'uid': '19', 'standardisedName': 'Operating Income (Loss)', 'parent_tid': '28', 'displayLevel': '0', 'valueAssigned': '-24897000', 'valueCalculated': 1892000, 'valueChosen': 1892000, 'checkPossible': True}, {'tid': '20', 'uid': '20', 'standardisedName': 'Non-Operating Income (Loss)', 'parent_tid': '28', 'displayLevel': '0', 'valueAssigned': '-1984000', 'valueCalculated': 1984000, 'valueChosen': 1984000, 'checkPossible': True}, {'tid': '21', 'uid': '21', 'standardisedName': 'Interest Expense, net', 'parent_tid': '20', 'displayLevel': '1', 'valueAssigned': '491000', 'valueCalculated': 0, 'valueChosen': '491000', 'checkPossible': False}, {'tid': '22', 'uid': '0', 'standardisedName': 'Interest Expense', 'parent_tid': '21', 'displayLevel': '2', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '23', 'uid': '0', 'standardisedName': 'Interest Income', 'parent_tid': '21', 'displayLevel': '2', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '24', 'uid': '0', 'standardisedName': 'Other Investment Income (Loss)', 'parent_tid': '20', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '25', 'uid': '0', 'standardisedName': 'Foreign Exchange Gain (Loss)', 'parent_tid': '20', 'displayLevel': '1', 'valueAssigned': '939000', 'valueCalculated': 0, 'valueChosen': '939000', 'checkPossible': False}, {'tid': '26', 'uid': '0', 'standardisedName': 'Income (Loss) from Affiliates', 'parent_tid': '20', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '27', 'uid': '0', 'standardisedName': 'Other Non-Operating Income (Loss)', 'parent_tid': '20', 'displayLevel': '1', 'valueAssigned': '554000', 'valueCalculated': 0, 'valueChosen': '554000', 'checkPossible': False}, {'tid': '28', 'uid': '28', 'standardisedName': 'Pretax Income (Loss), Adjusted', 'parent_tid': '43', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': 3876000, 'valueChosen': 3876000, 'checkPossible': False}, {'tid': '29', 'uid': '29', 'standardisedName': 'Abnormal Gains (Losses)', 'parent_tid': '43', 'displayLevel': '0', 'valueAssigned': '-26789000', 'valueCalculated': 0, 'valueChosen': '-26789000', 'checkPossible': False}, {'tid': '30', 'uid': '0', 'standardisedName': 'Acquired In-Process R&D', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '31', 'uid': '0', 'standardisedName': 'Merger / Acquisition Expense', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '32', 'uid': '0', 'standardisedName': 'Abnormal Derivatives', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '33', 'uid': '0', 'standardisedName': 'Disposal of Assets', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '34', 'uid': '0', 'standardisedName': 'Early extinguishment of Debt', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '35', 'uid': '0', 'standardisedName': 'Asset Write-Down', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '36', 'uid': '0', 'standardisedName': 'Impairment of Goodwill & Intangibles', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '37', 'uid': '0', 'standardisedName': 'Sale of Business', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '38', 'uid': '0', 'standardisedName': 'Legal Settlement', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '39', 'uid': '0', 'standardisedName': 'Restructuring Charges', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '40', 'uid': '0', 'standardisedName': 'Sale of and Unrealized Investments', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '41', 'uid': '0', 'standardisedName': 'Insurance Settlement', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '42', 'uid': '0', 'standardisedName': 'Other Abnormal Items', 'parent_tid': '29', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '43', 'uid': '43', 'standardisedName': 'Pretax Income (Loss)', 'parent_tid': '49', 'displayLevel': '0', 'valueAssigned': '-22913000', 'valueCalculated': -22913000, 'valueChosen': -22913000, 'checkPossible': True}, {'tid': '44', 'uid': '44', 'standardisedName': 'Income Tax (Expense) Benefit, net', 'parent_tid': '49', 'displayLevel': '0', 'valueAssigned': '4860000', 'valueCalculated': 0, 'valueChosen': '4860000', 'checkPossible': False}, {'tid': '45', 'uid': '0', 'standardisedName': 'Current Income Tax', 'parent_tid': '44', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '46', 'uid': '0', 'standardisedName': 'Deferred Income Tax', 'parent_tid': '44', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '47', 'uid': '0', 'standardisedName': 'Tax Allowance/Credit', 'parent_tid': '44', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '48', 'uid': '0', 'standardisedName': 'Income (Loss) from Affiliates, net of taxes', 'parent_tid': '49', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '49', 'uid': '49', 'standardisedName': 'Income (Loss) from Continuing Operations', 'parent_tid': '53', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': -18053000, 'valueChosen': -18053000, 'checkPossible': False}, {'tid': '50', 'uid': '50', 'standardisedName': 'Net Extraordinary Gains (Losses)', 'parent_tid': '53', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '51', 'uid': '51', 'standardisedName': 'Discontinued Operations', 'parent_tid': '50', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '52', 'uid': '0', 'standardisedName': 'XO & Accounting Charges & Other', 'parent_tid': '50', 'displayLevel': '1', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '53', 'uid': '53', 'standardisedName': 'Income (Loss) Including Minority Interest', 'parent_tid': '55', 'displayLevel': '0', 'valueAssigned': '-18053000', 'valueCalculated': -18053000, 'valueChosen': -18053000, 'checkPossible': True}, {'tid': '54', 'uid': '54', 'standardisedName': 'Minority Interest', 'parent_tid': '55', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '55', 'uid': '55', 'standardisedName': 'Net Income', 'parent_tid': '58', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': -18053000, 'valueChosen': -18053000, 'checkPossible': False}, {'tid': '56', 'uid': '56', 'standardisedName': 'Preferred Dividends', 'parent_tid': '58', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '57', 'uid': '0', 'standardisedName': 'Other Adjustments', 'parent_tid': '58', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': 0, 'valueChosen': None, 'checkPossible': False}, {'tid': '58', 'uid': '58', 'standardisedName': 'Net Income Available to Common Shareholders', 'parent_tid': '0', 'displayLevel': '0', 'valueAssigned': None, 'valueCalculated': -18053000, 'valueChosen': -18053000, 'checkPossible': False}]}

In [56]:
r_json["values"]

[{'tid': '1',
  'uid': '1',
  'standardisedName': 'Revenue',
  'parent_tid': '4',
  'displayLevel': '0',
  'valueAssigned': '278221000',
  'valueCalculated': 0,
  'valueChosen': '278221000',
  'checkPossible': False},
 {'tid': '3',
  'uid': '0',
  'standardisedName': 'Sales & Services Revenue',
  'parent_tid': '1',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '5',
  'uid': '0',
  'standardisedName': 'Financing Revenue',
  'parent_tid': '1',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '6',
  'uid': '0',
  'standardisedName': 'Other Revenue',
  'parent_tid': '1',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '2',
  'uid': '2',
  'standardisedName': 'Cost of revenue',
  'parent_tid': '4',
  'displayLevel': '0',
  'valueAssigned': '-73247000',
  'valueCalculated': 0,
  'valueChosen': '-73247000',
  'checkPossible': False},
 {'tid': '7',
  'uid': '0',
  'standardisedName': 'Cost of Goods & Services',
  'parent_tid': '2',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '8',
  'uid': '0',
  'standardisedName': 'Cost of Financing Revenue',
  'parent_tid': '2',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '9',
  'uid': '0',
  'standardisedName': 'Cost of Other Revenue',
  'parent_tid': '2',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '4',
  'uid': '4',
  'standardisedName': 'Gross Profit',
  'parent_tid': '19',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': 204974000,
  'valueChosen': 204974000,
  'checkPossible': False},
 {'tid': '10',
  'uid': '10',
  'standardisedName': 'Other Operating Income',
  'parent_tid': '19',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '11',
  'uid': '11',
  'standardisedName': 'Operating Expenses',
  'parent_tid': '19',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': -203082000,
  'valueChosen': -203082000,
  'checkPossible': False},
 {'tid': '12',
  'uid': '12',
  'standardisedName': 'Selling, General & Administrative',
  'parent_tid': '11',
  'displayLevel': '1',
  'valueAssigned': '-151898000',
  'valueCalculated': 0,
  'valueChosen': '-151898000',
  'checkPossible': False},
 {'tid': '13',
  'uid': '0',
  'standardisedName': 'Selling & Marketing',
  'parent_tid': '12',
  'displayLevel': '2',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '14',
  'uid': '0',
  'standardisedName': 'General & Administrative',
  'parent_tid': '12',
  'displayLevel': '2',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '15',
  'uid': '15',
  'standardisedName': 'Research & Development',
  'parent_tid': '11',
  'displayLevel': '1',
  'valueAssigned': '-51184000',
  'valueCalculated': 0,
  'valueChosen': '-51184000',
  'checkPossible': False},
 {'tid': '16',
  'uid': '16',
  'standardisedName': 'Depreciation & Amortization',
  'parent_tid': '11',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '17',
  'uid': '17',
  'standardisedName': 'Provision For Doubtful Accounts',
  'parent_tid': '11',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '18',
  'uid': '18',
  'standardisedName': 'Other Operating Expense',
  'parent_tid': '11',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '19',
  'uid': '19',
  'standardisedName': 'Operating Income (Loss)',
  'parent_tid': '28',
  'displayLevel': '0',
  'valueAssigned': '-24897000',
  'valueCalculated': 1892000,
  'valueChosen': 1892000,
  'checkPossible': True},
 {'tid': '20',
  'uid': '20',
  'standardisedName': 'Non-Operating Income (Loss)',
  'parent_tid': '28',
  'displayLevel': '0',
  'valueAssigned': '-1984000',
  'valueCalculated': 1984000,
  'valueChosen': 1984000,
  'checkPossible': True},
 {'tid': '21',
  'uid': '21',
  'standardisedName': 'Interest Expense, net',
  'parent_tid': '20',
  'displayLevel': '1',
  'valueAssigned': '491000',
  'valueCalculated': 0,
  'valueChosen': '491000',
  'checkPossible': False},
 {'tid': '22',
  'uid': '0',
  'standardisedName': 'Interest Expense',
  'parent_tid': '21',
  'displayLevel': '2',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '23',
  'uid': '0',
  'standardisedName': 'Interest Income',
  'parent_tid': '21',
  'displayLevel': '2',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '24',
  'uid': '0',
  'standardisedName': 'Other Investment Income (Loss)',
  'parent_tid': '20',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '25',
  'uid': '0',
  'standardisedName': 'Foreign Exchange Gain (Loss)',
  'parent_tid': '20',
  'displayLevel': '1',
  'valueAssigned': '939000',
  'valueCalculated': 0,
  'valueChosen': '939000',
  'checkPossible': False},
 {'tid': '26',
  'uid': '0',
  'standardisedName': 'Income (Loss) from Affiliates',
  'parent_tid': '20',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '27',
  'uid': '0',
  'standardisedName': 'Other Non-Operating Income (Loss)',
  'parent_tid': '20',
  'displayLevel': '1',
  'valueAssigned': '554000',
  'valueCalculated': 0,
  'valueChosen': '554000',
  'checkPossible': False},
 {'tid': '28',
  'uid': '28',
  'standardisedName': 'Pretax Income (Loss), Adjusted',
  'parent_tid': '43',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': 3876000,
  'valueChosen': 3876000,
  'checkPossible': False},
 {'tid': '29',
  'uid': '29',
  'standardisedName': 'Abnormal Gains (Losses)',
  'parent_tid': '43',
  'displayLevel': '0',
  'valueAssigned': '-26789000',
  'valueCalculated': 0,
  'valueChosen': '-26789000',
  'checkPossible': False},
 {'tid': '30',
  'uid': '0',
  'standardisedName': 'Acquired In-Process R&D',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '31',
  'uid': '0',
  'standardisedName': 'Merger / Acquisition Expense',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '32',
  'uid': '0',
  'standardisedName': 'Abnormal Derivatives',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '33',
  'uid': '0',
  'standardisedName': 'Disposal of Assets',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '34',
  'uid': '0',
  'standardisedName': 'Early extinguishment of Debt',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '35',
  'uid': '0',
  'standardisedName': 'Asset Write-Down',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '36',
  'uid': '0',
  'standardisedName': 'Impairment of Goodwill & Intangibles',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '37',
  'uid': '0',
  'standardisedName': 'Sale of Business',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '38',
  'uid': '0',
  'standardisedName': 'Legal Settlement',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '39',
  'uid': '0',
  'standardisedName': 'Restructuring Charges',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '40',
  'uid': '0',
  'standardisedName': 'Sale of and Unrealized Investments',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '41',
  'uid': '0',
  'standardisedName': 'Insurance Settlement',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '42',
  'uid': '0',
  'standardisedName': 'Other Abnormal Items',
  'parent_tid': '29',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '43',
  'uid': '43',
  'standardisedName': 'Pretax Income (Loss)',
  'parent_tid': '49',
  'displayLevel': '0',
  'valueAssigned': '-22913000',
  'valueCalculated': -22913000,
  'valueChosen': -22913000,
  'checkPossible': True},
 {'tid': '44',
  'uid': '44',
  'standardisedName': 'Income Tax (Expense) Benefit, net',
  'parent_tid': '49',
  'displayLevel': '0',
  'valueAssigned': '4860000',
  'valueCalculated': 0,
  'valueChosen': '4860000',
  'checkPossible': False},
 {'tid': '45',
  'uid': '0',
  'standardisedName': 'Current Income Tax',
  'parent_tid': '44',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '46',
  'uid': '0',
  'standardisedName': 'Deferred Income Tax',
  'parent_tid': '44',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '47',
  'uid': '0',
  'standardisedName': 'Tax Allowance/Credit',
  'parent_tid': '44',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '48',
  'uid': '0',
  'standardisedName': 'Income (Loss) from Affiliates, net of taxes',
  'parent_tid': '49',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '49',
  'uid': '49',
  'standardisedName': 'Income (Loss) from Continuing Operations',
  'parent_tid': '53',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': -18053000,
  'valueChosen': -18053000,
  'checkPossible': False},
 {'tid': '50',
  'uid': '50',
  'standardisedName': 'Net Extraordinary Gains (Losses)',
  'parent_tid': '53',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '51',
  'uid': '51',
  'standardisedName': 'Discontinued Operations',
  'parent_tid': '50',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '52',
  'uid': '0',
  'standardisedName': 'XO & Accounting Charges & Other',
  'parent_tid': '50',
  'displayLevel': '1',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '53',
  'uid': '53',
  'standardisedName': 'Income (Loss) Including Minority Interest',
  'parent_tid': '55',
  'displayLevel': '0',
  'valueAssigned': '-18053000',
  'valueCalculated': -18053000,
  'valueChosen': -18053000,
  'checkPossible': True},
 {'tid': '54',
  'uid': '54',
  'standardisedName': 'Minority Interest',
  'parent_tid': '55',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '55',
  'uid': '55',
  'standardisedName': 'Net Income',
  'parent_tid': '58',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': -18053000,
  'valueChosen': -18053000,
  'checkPossible': False},
 {'tid': '56',
  'uid': '56',
  'standardisedName': 'Preferred Dividends',
  'parent_tid': '58',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '57',
  'uid': '0',
  'standardisedName': 'Other Adjustments',
  'parent_tid': '58',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': 0,
  'valueChosen': None,
  'checkPossible': False},
 {'tid': '58',
  'uid': '58',
  'standardisedName': 'Net Income Available to Common Shareholders',
  'parent_tid': '0',
  'displayLevel': '0',
  'valueAssigned': None,
  'valueCalculated': -18053000,
  'valueChosen': -18053000,
  'checkPossible': False}]

In [54]:
df_pl_std = pd.DataFrame(r_json["values"])
df_pl_std

,checkPossible,displayLevel,parent_tid,standardisedName,tid,uid,valueAssigned,valueCalculated,valueChosen
0,False,0,4,Revenue,1,1,155545000,0,155545000
1,False,1,1,Sales & Services Revenue,3,0,None,0,None
2,False,1,1,Financing Revenue,5,0,None,0,None
3,False,1,1,Other Revenue,6,0,None,0,None
4,False,0,4,Cost of revenue,2,2,-56836000,0,-56836000
5,False,1,2,Cost of Goods & Services,7,0,None,0,None
6,False,1,2,Cost of Financing Revenue,8,0,None,0,None
7,False,1,2,Cost of Other Revenue,9,0,None,0,None
8,False,0,19,Gross Profit,4,4,None,98709000,98709000
9,False,0,19,Other Operating Income,10,10,None,0,None
10,False,0,19,Operating Expenses,11,11,None,-154890000,-154890000
11,False,1,11,"Selling, General & Administrative",12,12,-107390000,0,-107390000
12,False,2,12,Selling & Marketing,13,0,None,0,None
13,False,2,12,General & Administrative,14,0,None,0,None
14,False,1,11,Research & Development,15,15,-47500000,0,-47500000
15,False,1,11,Depreciation & Amortization,16,16,None,0,None
16,False,1,11,Provision For Doubtful Accounts,17,17,None,0,None
17,False,1,11,Other Operating Expense,18,18,None,0,None
18,True,0,28,Operating Income (Loss),19,19,-156976000,-56181000,-56181000
19,True,0,28,Non-Operating Income (Loss),20,20,-431000,431000,431000
20,False,1,20,"Interest Expense, net",21,21,908000,0,908000
21,False,2,21,Interest Expense,22,0,None,0,None
22,False,2,21,Interest Income,23,0,None,0,None
23,False,1,20,Other Investment Income (Loss),24,0,None,0,None
24,False,1,20,Foreign Exchange Gain (Loss),25,0,-1165000,0,-1165000
25,False,1,20,Income (Loss) from Affiliates,26,0,None,0,None
26,False,1,20,Other Non-Operating Income (Loss),27,0,688000,0,688000
27,False,0,43,"Pretax Income (Loss), Adjusted",28,28,None,-55750000,-55750000
28,False,0,43,Abnormal Gains (Losses),29,29,-100795000,0,-100795000
29,False,1,29,Acquired In-Process R&D,30,0,None,0,None
30,False,1,29,Merger / Acquisition Expense,31,0,None,0,None
31,False,1,29,Abnormal Derivatives,32,0,None,0,None
32,False,1,29,Disposal of Assets,33,0,None,0,None
33,False,1,29,Early extinguishment of Debt,34,0,None,0,None
34,False,1,29,Asset Write-Down,35,0,None,0,None
35,False,1,29,Impairment of Goodwill & Intangibles,36,0,None,0,None
36,False,1,29,Sale of Business,37,0,None,0,None
37,False,1,29,Legal Settlement,38,0,None,0,None
38,False,1,29,Restructuring Charges,39,0,None,0,None
39,False,1,29,Sale of and Unrealized Investments,40,0,None,0,None
40,False,1,29,Insurance Settlement,41,0,None,0,None
41,False,1,29,Other Abnormal Items,42,0,None,0,None
42,True,0,49,Pretax Income (Loss),43,43,-156545000,-156545000,-156545000
43,False,0,49,"Income Tax (Expense) Benefit, net",44,44,1762000,0,1762000
44,False,1,44,Current Income Tax,45,0,None,0,None
45,False,1,44,Deferred Income Tax,46,0,None,0,None
46,False,1,44,Tax Allowance/Credit,47,0,None,0,None
47,False,0,49,"Income (Loss) from Affiliates, net of taxes",48,0,None,0,None
48,False,0,53,Income (Loss) from Continuing Operations,49,49,None,-154783000,-154783000
49,False,0,53,Net Extraordinary Gains (Losses),50,50,None,0,None
50,False,1,50,Discontinued Operations,51,51,None,0,None
51,False,1,50,XO & Accounting Charges & Other,52,0,None,0,None
52,True,0,55,Income (Loss) Including Minority Interest,53,53,-154783000,-154783000,-154783000
53,False,0,55,Minority Interest,54,54,None,0,None
54,False,0,58,Net Income,55,55,None,-154783000,-154783000
55,False,0,58,Preferred Dividends,56,56,None,0,None
56,False,0,58,Other Adjustments,57,0,None,0,None
57,False,0,0,Net Income Available to Common Shareholders,58,58,None,-154783000,-154783000

In [57]:
#TTM financial ratios

companyId = df.loc["RUBI"]["simId"]

base_url = "https://simfin.com/api/v1/companies/id/{0}/ratios?api-key={1}".format(companyId, YOUR_API_KEY)
r = requests.get(base_url)
r_json = r.json()
print(r_json)

[{'indicatorId': '0-31', 'indicatorName': 'Last Closing Price', 'value': '3.96', 'period': None, 'fyear': None, 'currency': 'USD', 'period-end-date': '2018-08-14'}, {'indicatorId': '0-64', 'indicatorName': 'Common Shares Outstanding', 'value': '50750139', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': '2018-07-26'}, {'indicatorId': '0-65', 'indicatorName': 'Preferred Shares Outstanding', 'value': None, 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '0-66', 'indicatorName': 'Average Shares Outstanding, basic', 'value': '49763250', 'period': 'TTM', 'fyear': 2018, 'currency': None, 'period-end-date': '2018-06-30'}, {'indicatorId': '0-67', 'indicatorName': 'Average Shares Outstanding, diluted', 'value': '49763250', 'period': 'TTM', 'fyear': 2018, 'currency': None, 'period-end-date': '2018-06-30'}, {'indicatorId': '1-1', 'indicatorName': 'Revenues', 'value': '120132000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-2', 'indicatorName': 'Cost of Goods Sold', 'value': '58277000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-4', 'indicatorName': 'Gross Profit', 'value': '61855000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-11', 'indicatorName': 'Operating Expenses', 'value': '140617000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-12', 'indicatorName': 'Selling, General and Administrative', 'value': '98175000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-15', 'indicatorName': 'Research & Development Expenses', 'value': '42442000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-19', 'indicatorName': 'Operating Income (EBIT)', 'value': '-78762000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-21', 'indicatorName': 'Interest Expense, net', 'value': '-1058000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-28', 'indicatorName': 'Pretax Income (adjusted)', 'value': '-77046000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-43', 'indicatorName': 'Pretax Income', 'value': '-175322000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-44', 'indicatorName': 'Income Taxes', 'value': '-2134000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-49', 'indicatorName': 'Income from Continuing Operations', 'value': '-173188000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '1-58', 'indicatorName': 'Net Income (common shareholders)', 'value': '-173188000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-1', 'indicatorName': 'Cash and Cash-equivalents', 'value': '104319000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-5', 'indicatorName': 'Receivables, net', 'value': '153163000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-21', 'indicatorName': 'Total Current Assets', 'value': '266523000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-22', 'indicatorName': 'Property, Plant and Equipment, net', 'value': '36571000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-41', 'indicatorName': 'Total Assets', 'value': '330398000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-43', 'indicatorName': 'Accounts payable', 'value': '198504000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-47', 'indicatorName': 'Current Debt', 'value': '0', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-57', 'indicatorName': 'Total Current Liabilities', 'value': '201403000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-58', 'indicatorName': 'Non-current Debt', 'value': '0', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-73', 'indicatorName': 'Total Liabilities', 'value': '202734000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-74', 'indicatorName': 'Preferred Equity', 'value': '0', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-76', 'indicatorName': 'Common Stock', 'value': '0', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-82', 'indicatorName': 'Equity before minorities', 'value': '127664000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-83', 'indicatorName': 'Minority Interest', 'value': '0', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '2-84', 'indicatorName': 'Total Equity', 'value': '127664000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '3-2', 'indicatorName': 'Depreciation & Amortisation', 'value': '34837000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '3-7', 'indicatorName': 'Change in Working Capital', 'value': '16046000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '3-13', 'indicatorName': 'Operating Cash Flow', 'value': '-12360000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '3-14', 'indicatorName': 'Net Change in PP&E & Intangibles', 'value': '-28815000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '3-31', 'indicatorName': 'Investing Cash Flow', 'value': '-80093000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '3-32', 'indicatorName': 'Dividends paid', 'value': '0', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '3-43', 'indicatorName': 'Financing Cash Flow', 'value': '-630000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '3-46', 'indicatorName': 'Net Change in Cash', 'value': '-93071000', 'period': 'TTM', 'fyear': 2018, 'currency': 'USD', 'period-end-date': '2018-06-30'}, {'indicatorId': '4-11', 'indicatorName': 'Market Capitalisation', 'value': '200970550.4400', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-10', 'indicatorName': 'EBITDA', 'value': '-43925000.0000', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-6', 'indicatorName': 'Total Debt', 'value': '0.0000', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-25', 'indicatorName': 'Free Cash Flow', 'value': '-54560000.0000', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-0', 'indicatorName': 'Gross Margin', 'value': '0.5149', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-1', 'indicatorName': 'Operating Margin', 'value': '-0.6556', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-2', 'indicatorName': 'Net Profit Margin', 'value': '-1.4416', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-7', 'indicatorName': 'Return on Equity', 'value': '-1.3566', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-9', 'indicatorName': 'Return on Assets', 'value': '-0.5242', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-28', 'indicatorName': 'Free Cash Flow to Net Income', 'value': '0.3150', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-3', 'indicatorName': 'Current Ratio', 'value': '1.3233', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-4', 'indicatorName': 'Liabilities to Equity Ratio', 'value': '1.5880', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-5', 'indicatorName': 'Debt to Assets Ratio', 'value': '0.0000', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-12', 'indicatorName': 'Earnings per Share, Basic', 'value': '-3.4802', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-13', 'indicatorName': 'Earnings per Share, Diluted', 'value': '-3.4802', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-17', 'indicatorName': 'Sales per Share', 'value': '2.4141', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-18', 'indicatorName': 'Book Value per Share', 'value': '2.5654', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-26', 'indicatorName': 'Free Cash Flow per Share', 'value': '-1.0964', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-29', 'indicatorName': 'Dividends per Share', 'value': '0.0000', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-14', 'indicatorName': 'Price to Earnings Ratio', 'value': '-1.1379', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-15', 'indicatorName': 'Price to Sales Ratio', 'value': '1.6404', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-16', 'indicatorName': 'Price to Book Value', 'value': '1.5436', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-27', 'indicatorName': 'Price to Free Cash Flow', 'value': '-3.6118', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-11', 'indicatorName': 'Market Capitalisation', 'value': '200970550.4400', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-20', 'indicatorName': 'Enterprise Value', 'value': '96651550.4400', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-21', 'indicatorName': 'EV/EBITDA', 'value': '-2.2004', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-22', 'indicatorName': 'EV/Sales', 'value': '0.8045', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-31', 'indicatorName': 'EV/FCF', 'value': '-1.7715', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-23', 'indicatorName': 'Book to Market Value', 'value': '0.6352', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-24', 'indicatorName': 'Operating Income/EV', 'value': '-0.8149', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}, {'indicatorId': '4-30', 'indicatorName': 'Pietroski F-Score', 'value': '0.0000', 'period': None, 'fyear': None, 'currency': None, 'period-end-date': None}]

In [58]:
df_ratio = pd.DataFrame(r_json)
df_ratio

,currency,fyear,indicatorId,indicatorName,period,period-end-date,value
0,USD,NaN,0-31,Last Closing Price,None,2018-08-14,3.96
1,None,NaN,0-64,Common Shares Outstanding,None,2018-07-26,50750139
2,None,NaN,0-65,Preferred Shares Outstanding,None,None,None
3,None,2018.0,0-66,"Average Shares Outstanding, basic",TTM,2018-06-30,49763250
4,None,2018.0,0-67,"Average Shares Outstanding, diluted",TTM,2018-06-30,49763250
5,USD,2018.0,1-1,Revenues,TTM,2018-06-30,120132000
6,USD,2018.0,1-2,Cost of Goods Sold,TTM,2018-06-30,58277000
7,USD,2018.0,1-4,Gross Profit,TTM,2018-06-30,61855000
8,USD,2018.0,1-11,Operating Expenses,TTM,2018-06-30,140617000
9,USD,2018.0,1-12,"Selling, General and Administrative",TTM,2018-06-30,98175000
10,USD,2018.0,1-15,Research & Development Expenses,TTM,2018-06-30,42442000
11,USD,2018.0,1-19,Operating Income (EBIT),TTM,2018-06-30,-78762000
12,USD,2018.0,1-21,"Interest Expense, net",TTM,2018-06-30,-1058000
13,USD,2018.0,1-28,Pretax Income (adjusted),TTM,2018-06-30,-77046000
14,USD,2018.0,1-43,Pretax Income,TTM,2018-06-30,-175322000
15,USD,2018.0,1-44,Income Taxes,TTM,2018-06-30,-2134000
16,USD,2018.0,1-49,Income from Continuing Operations,TTM,2018-06-30,-173188000
17,USD,2018.0,1-58,Net Income (common shareholders),TTM,2018-06-30,-173188000
18,USD,2018.0,2-1,Cash and Cash-equivalents,TTM,2018-06-30,104319000
19,USD,2018.0,2-5,"Receivables, net",TTM,2018-06-30,153163000
20,USD,2018.0,2-21,Total Current Assets,TTM,2018-06-30,266523000
21,USD,2018.0,2-22,"Property, Plant and Equipment, net",TTM,2018-06-30,36571000
22,USD,2018.0,2-41,Total Assets,TTM,2018-06-30,330398000
23,USD,2018.0,2-43,Accounts payable,TTM,2018-06-30,198504000
24,USD,2018.0,2-47,Current Debt,TTM,2018-06-30,0
25,USD,2018.0,2-57,Total Current Liabilities,TTM,2018-06-30,201403000
26,USD,2018.0,2-58,Non-current Debt,TTM,2018-06-30,0
27,USD,2018.0,2-73,Total Liabilities,TTM,2018-06-30,202734000
28,USD,2018.0,2-74,Preferred Equity,TTM,2018-06-30,0
29,USD,2018.0,2-76,Common Stock,TTM,2018-06-30,0
...,...,...,...,...,...,...,...
42,None,NaN,4-10,EBITDA,None,None,-43925000.0000
43,None,NaN,4-6,Total Debt,None,None,0.0000
44,None,NaN,4-25,Free Cash Flow,None,None,-54560000.0000
45,None,NaN,4-0,Gross Margin,None,None,0.5149
46,None,NaN,4-1,Operating Margin,None,None,-0.6556
47,None,NaN,4-2,Net Profit Margin,None,None,-1.4416
48,None,NaN,4-7,Return on Equity,None,None,-1.3566
49,None,NaN,4-9,Return on Assets,None,None,-0.5242
50,None,NaN,4-28,Free Cash Flow to Net Income,None,None,0.3150
51,None,NaN,4-3,Current Ratio,None,None,1.3233
52,None,NaN,4-4,Liabilities to Equity Ratio,None,None,1.5880
53,None,NaN,4-5,Debt to Assets Ratio,None,None,0.0000
54,None,NaN,4-12,"Earnings per Share, Basic",None,None,-3.4802
55,None,NaN,4-13,"Earnings per Share, Diluted",None,None,-3.4802
56,None,NaN,4-17,Sales per Share,None,None,2.4141
57,None,NaN,4-18,Book Value per Share,None,None,2.5654
58,None,NaN,4-26,Free Cash Flow per Share,None,None,-1.0964
59,None,NaN,4-29,Dividends per Share,None,None,0.0000
60,None,NaN,4-14,Price to Earnings Ratio,None,None,-1.1379
61,None,NaN,4-15,Price to Sales Ratio,None,None,1.6404
62,None,NaN,4-16,Price to Book Value,None,None,1.5436
63,None,NaN,4-27,Price to Free Cash Flow,None,None,-3.6118
64,None,NaN,4-11,Market Capitalisation,None,None,200970550.4400
65,None,NaN,4-20,Enterprise Value,None,None,96651550.4400
66,None,NaN,4-21,EV/EBITDA,None,None,-2.2004
67,None,NaN,4-22,EV/Sales,None,None,0.8045
68,None,NaN,4-31,EV/FCF,None,None,-1.7715
69,None,NaN,4-23,Book to Market Value,None,None,0.6352
70,None,NaN,4-24,Operating Income/EV,None,None,-0.8149
71,None,NaN,4-30,Pietroski F-Score,None,None,0.0000